version: '3.8'

services:
  meatify:
    image: meatify-app:latest
    ports:
      - "3000:3000"
    volumes:
      # Mount persistent data directory for session sharing
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
